In [5]:
#Task-1 Save the employee ID in separate ID array ,one for each department and print them.
import numpy as np
HR=np.array(np.arange(1,4))
print(HR)  
#Interpretation:
#Created and printed the array of employee ID of HR department.

[1 2 3]


In [7]:
IT=np.array(np.arange(4,19))
print(IT)  
#Interpretation:
#Created and printed the array of employee ID of IT department.

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [9]:
Finance=np.array(np.arange(19,24))
print(Finance)   
#Interpretation:
#Created and printed the array of employee ID of Finance department.

[19 20 21 22 23]


In [11]:
Sales=np.array(np.arange(24,31))
print(Sales)  
#Interpretation:
#Created and printed the array of employee ID of Sales department.

[24 25 26 27 28 29 30]


In [13]:
#Task-2   Create four different ID array to hold only the salaries of employees:
HR_sal=np.array([50000,60000,57000])
print(HR_sal)  

#Interpretation:
#Assigned salary for each employees in HR department.

[50000 60000 57000]


In [15]:
IT_sal=np.array([67000]*15)
print(IT_sal)   

#Interpretation:
#Assigned salary for each employees in IT department.
#All 15 employees got same salary=67000.

[67000 67000 67000 67000 67000 67000 67000 67000 67000 67000 67000 67000
 67000 67000 67000]


In [17]:
Fin_sal=np.array([60000,65000,50000,70000,87000])
print(Fin_sal)

#Interpretation:
#Assigned salary for each employees in Finance department.

[60000 65000 50000 70000 87000]


In [19]:
Sales_sal=np.array([50000,60000,65000,90000,56000,65000,71000])
print(Sales_sal)

#Interpretation:
#Assigned salary for each employees in Sales department.

[50000 60000 65000 90000 56000 65000 71000]


In [21]:
#Task-3 Calculate department-wise average salary of all 30 employees:
HR_sal.mean()  

#Interpretation:
#Displayed HR department average salary.

55666.666666666664

In [23]:
IT_sal.mean()

#Interpretation:
#Displayed IT department average salary.

67000.0

In [25]:
Fin_sal.mean()

#Interpretation:
#Displayed Finance department average salary.

66400.0

In [27]:
Sales_sal.mean()

#Interpretation:
#Displayed Sales department average salary.

65285.71428571428

In [29]:
#Department with highest average salary expense on employees:
a=print(max(HR_sal))

60000


In [31]:
b=print(max(IT_sal))

67000


In [33]:
c=print(max(Fin_sal))

87000


In [35]:
d=print(max(Sales_sal))

90000


In [63]:
#Department with highest average salary expense on employees:
v=max(HR_sal.mean(),IT_sal.mean(),Fin_sal.mean(),Sales_sal.mean())
v

67000.0

In [43]:
#Task-4 List the highest salaries in HR and Finance departments:
np.max(HR_sal)

#Interpretation:
#Displayed the highest salary of HR department.

60000

In [45]:
np.max(Fin_sal)

#Interpretation:
#Displayed the highest salary of HR department.

87000

In [47]:
#Task-5 The company has decided to joining/signing bonus worth 5% of gross salary
#to those employees who belongs to the IT department.Update the salary of such employees after adding the bonus.Display the]
#updated salaries:

IT_sal=np.array([67000]*15)
IT_sal

bonus=5/100

update=IT_sal*bonus

x=update+IT_sal
x             

#Interpretation:
#Updated the salary of employees in IT dept by adding the bonus. Thus, displayed the updated salaries.

array([70350., 70350., 70350., 70350., 70350., 70350., 70350., 70350.,
       70350., 70350., 70350., 70350., 70350., 70350., 70350.])

In [49]:
y=sum(update+IT_sal)
y #Total of salaries after updated.

1055250.0

In [235]:
sum(x)  #Total of salaries after updated.

1055250.0

In [7]:
#University admission decision:

#Task-1 Import the data file into 2D array.Display the total number of rows and columns in the array:

adm_data=np.genfromtxt(r'DS1_C4_S1_AdmissionPredict_Data_Practice__1_.csv',delimiter=',',skip_header=True)
adm_data     

array([[  1.  , 337.  , 118.  , ...,   9.65,   1.  ,   0.92],
       [  2.  , 324.  , 107.  , ...,   8.87,   1.  ,   0.76],
       [  3.  , 316.  , 104.  , ...,   8.  ,   1.  ,   0.72],
       ...,
       [398.  , 330.  , 116.  , ...,   9.45,   1.  ,   0.91],
       [399.  , 312.  , 103.  , ...,   8.78,   0.  ,   0.67],
       [400.  , 333.  , 117.  , ...,   9.66,   1.  ,   0.95]])

In [9]:
row=adm_data.shape[0]
print('Row:',row)

column=adm_data.shape[1]
print('Column:',column)

#Interpretation:
#Row=400 and Column=9
#Displayed the total number of rows and columns in 2D array.

Row: 400
Column: 9


In [11]:
#Task-2 Display the GRE score of all the students:NOTE:Slice only one column from 2D array:
adm_data[:,1]   

#Interpretation:
#Displayed all students GRE score.

array([337., 324., 316., 322., 314., 330., 321., 308., 302., 323., 325.,
       327., 328., 307., 311., 314., 317., 319., 318., 303., 312., 325.,
       328., 334., 336., 340., 322., 298., 295., 310., 300., 327., 338.,
       340., 331., 320., 299., 300., 304., 307., 308., 316., 313., 332.,
       326., 322., 329., 339., 321., 327., 313., 312., 334., 324., 322.,
       320., 316., 298., 300., 311., 309., 307., 304., 315., 325., 325.,
       327., 316., 318., 328., 332., 336., 321., 314., 314., 329., 327.,
       301., 296., 294., 312., 340., 320., 322., 340., 319., 315., 317.,
       314., 316., 318., 299., 298., 301., 303., 304., 306., 331., 332.,
       323., 322., 312., 314., 317., 326., 316., 329., 338., 331., 304.,
       305., 321., 301., 320., 311., 310., 299., 290., 296., 327., 335.,
       334., 310., 308., 301., 300., 323., 319., 326., 333., 339., 303.,
       309., 323., 333., 314., 312., 316., 326., 318., 329., 332., 331.,
       340., 325., 320., 315., 326., 339., 311., 33

In [13]:
#Task-3 Find total number of students who have GRE score greater than 320:
x=adm_data[adm_data[:,1]>320]
print(x)

y=adm_data[adm_data[:,1]>320].shape[0]
print('Total row:',y)

z=adm_data[adm_data[:,1]>320].shape[1]
print('Total column:',z)

#Interpretation:
#Under this task I has used shape function to find the total number of students whose grace marks is greater than 320.

[[  1.   337.   118.   ...   9.65   1.     0.92]
 [  2.   324.   107.   ...   8.87   1.     0.76]
 [  4.   322.   110.   ...   8.67   1.     0.8 ]
 ...
 [397.   325.   107.   ...   9.11   1.     0.84]
 [398.   330.   116.   ...   9.45   1.     0.91]
 [400.   333.   117.   ...   9.66   1.     0.95]]
Total row: 163
Total column: 9


In [15]:
#Task-4 What is the chance of admission of student who have a TOEFL score greater than 110?Display the 
#admission chance as percentage number by multiplying each value in the output by 100:
#Hint:Identify the index location of students who satisfying the above condition.

chance_admission_percent=adm_data[adm_data[:,2]>110][:,8]*100
print(chance_admission_percent)

#Interpretation:
#Under this task I used slicing to find the chance admission column and TOFEL score whose TOFEL score is greater than 110 
#even multiplied the chance admit with 100 to show as a percentage and printed the answer.

[92. 90. 84. 78. 70. 94. 95. 97. 94. 91. 90. 94. 87. 91. 86. 89. 78. 78.
 72. 52. 55. 61. 78. 94. 96. 93. 72. 74. 96. 92. 94. 86. 90. 79. 74. 87.
 91. 93. 94. 94. 85. 78. 84. 92. 96. 79. 89. 80. 90. 92. 97. 80. 81. 83.
 96. 93. 94. 86. 81. 89. 89. 87. 85. 90. 89. 93. 93. 88. 90. 86. 94. 97.
 97. 95. 96. 94. 93. 91. 76. 71. 82. 91. 88. 85. 86. 70. 76. 77. 93. 85.
 90. 70. 83. 89. 80. 94. 93. 92. 89. 86. 90. 71. 80. 79. 80. 81. 80. 80.
 83. 94. 93. 91. 86. 95. 96. 96. 84. 89. 91. 95.]


In [39]:
#Task-5 The university decided to offer scholarship worth $1000 to all students who have GRE score greater than 315,
#TOFEL score greater than 115 and have some research experience.Determine the total number of students eligible for the 
#scholarship.Also display the serial number of these students.
#Hint:Identify the index position of the rows satisfying the above condition and then use this data to find a serial number of students.


adm_data[(adm_data[:,1]>315) & (adm_data[:,2]>115) & (adm_data[:,7]==1)].shape[0]   

#Interpretation:
#Displayed total number of students eligible for scholarship is 41.

41